
.PHONY: all clean cleanall

all:
	@$(MAKE) -C template
#	@$(MAKE) -C reactor

clean:
	@$(MAKE) clean -C template
#	@$(MAKE) clean -C reactor

cleanall:
	@$(MAKE) cleanall -C template
#	@$(MAKE) cleanall -C reactor
