
.PHONY: all clean cleanall

all:
	@$(MAKE) -C basic
	@$(MAKE) -C large_block

clean:
	@$(MAKE) clean -C basic
	@$(MAKE) clean -C large_block

cleanall:
	@$(MAKE) cleanall -C basic
	@$(MAKE) cleanall -C large_block
