
.PHONY: all clean cleanall

all:
	@$(MAKE) -C esma_echo_server
	@$(MAKE) -C esma_echo_server_2

clean:
	@$(MAKE) clean -C esma_echo_server
	@$(MAKE) clean -C esma_echo_server_2

cleanall:
	@$(MAKE) cleanall -C esma_echo_server
	@$(MAKE) cleanall -C esma_echo_server_2
